version: "3.8"
services:
  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      - POSTRGRESS_DB=postgres
  db:
    container_name: db
    image: postgres:13.3
    restart: always
    environment:
      - POSTGRES_DB=postgres #имя моей бд
      - POSTGRES_USER=postgres   #юзер бд
      - POSTGRES_PASSWORD=asdqwe #пароль к локальной бд
    ports:
      - '5430:5430'    #порт для бд, по умолчанию 5432
