version: "3.8"
services:
  backend:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
    restart: always    # при несанкционированных падениях апки, будет произведен рестарт
    depends_on:
      - db   # загружает апку после полной загрузки бд, а не произвольно
  db:
    container_name: db
    image: postgres:13.3
    restart: always
    environment:
      - POSTGRES_DB=postgres # имя моей бд
      - POSTGRES_USER=postgres   # юзер бд
      - POSTGRES_PASSWORD=postgres # пароль к локальной бд
    ports:
      - 5432:5432    # порт для бд, по умолчанию 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql