version: "3.8"
services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      - POSTGRES_DB=postgres #имя моей бд
      - POSTGRES_USER=postgres   #юзер бд
      - POSTGRES_PASSWORD=asdqwe #пароль к локальной бд
    ports:
    - '5432:5432'    #порт для бд, по умолчанию 5432
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql