# Spring Boot configuration
spring:
#   profiles:
#     active: development
  # Security configuration
#   security:
#     user:
#       name: user
#       password: user
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
# Logger configuration
logging:
  pattern:
    console: "%d [%t] %-5level %logger{36} - %msg%n"
    file: "%d [%t] %-5level %logger{36} - %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
  file.name: logs/Discount-exadel-one-to-many-service.log
# Server configuration
server:
  port: 8080



