spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
jwt:
  token:
    expiration:
      seconds:
        access: 120
        refresh: 3600
    encryption:
      key: encryptionSecret
cors:
  hosts:
    - http://localhost:4200
server:
  port: ${PORT}