spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
jwt:
  expiration:
    access: 120
    refresh: 3600
  encryption:
    encryption-key: ${JWT_ENCRYPTION_KEY}
cors:
  accepted-origins: ${CORS_ACCEPTED_ORIGINS}
server:
  port: ${PORT}
cloud:
  aws:
    s3:
      credentials:
        access-key: ${CLOUD_AWS_S3_CREDENTIALS_ACCESS_KEY}
        secret-key: ${CLOUD_AWS_S3_CREDENTIALS_SECRET_KEY}