spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
  mail:
    default-encoding: UTF-8
    protocol: smtp
    port: 587
    host: smtp.gmail.com
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
jwt:
  expiration:
    access: 120
    refresh: 3600
  encryption:
    encryption-key: ${JWT_ENCRYPTION_KEY}
cors:
  accepted-origins: ${CORS_ACCEPTED_ORIGINS}
server:
  port: ${PORT}
cloud:
  aws:
    s3:
      credentials:
        access-key: ${CLOUD_AWS_S3_CREDENTIALS_ACCESS_KEY}
        secret-key: ${CLOUD_AWS_S3_CREDENTIALS_SECRET_KEY}
