spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver

jwt:
  access:
    expiration:
      seconds: 120
  refresh:
    expiration:
      seconds: 3600
  encryption:
    key: encryptionSecret